-- CreateTable
CREATE TABLE `business_settings` (
    `BUSINESS_SETTINGS_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `BUSINESS_ID` INTEGER NOT NULL,
    `DELIVERY_RANGE_ZIP_CODES` TEXT NULL,
    `CREATION_DATETIME` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `LAST_UPDATE_DATETIME` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    UNIQUE INDEX `BusinessSettings_businessId_key`(`BUSINESS_ID`),
    PRIMARY KEY (`BUSINESS_SETTINGS_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `business_settings`
ADD CONSTRAINT `BusinessSettings_businessId_fkey`
FOREIGN KEY (`BUSINESS_ID`) REFERENCES `business`(`BUSINESS_ID`)
ON DELETE CASCADE ON UPDATE CASCADE;
