import Navbar from "@/components/core/Navbar";
import Footer from "@/components/core/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Dashboard | Foodeez",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="max-w-[1440px] mx-auto">
            <Navbar />
            <div className="min-h-screen">
                {children}
            </div>
            <Footer />
        </div>
    );
}
