import Navbar from "@/components/core/Navbar";
import Footer from "@/components/core/Footer";
import DashboardBreadcrumb from "@/components/core/DashboardBreadcrumb";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Dashboard | Foodeez",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="max-w-[1440px] mx-auto">
            <Navbar />
            <div className="min-h-screen bg-gray-100">
                <div className="px-4 sm:px-6 lg:px-8 py-4">
                    <DashboardBreadcrumb />
                </div>
                {children}
            </div>
            <Footer />
        </div>
    );
}
